### ISSUE TITLE
您好，请问程序运行出现Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED原因在哪里

### ISSUE THREAD

**Issue by binaryLongZaiTian** [RDShi/voiceprint#1]
已经配置好了环境，cuda9+cudnn7.3，路径和数据集设置好了之后运行发现出现了上述问题，请问是哪里出现的问题？您能说下您的环境配置吗

**Comment by RDShi** [comment]
抱歉刚看到，不知道你的问题是否解决了
我没遇到过类似问题，代码也在多个机器上跑过，下面是我觉得可能引起问题的原因：
- 检查一下运行代码的环境是否有 GPU，如果有安装 nvida 驱动了吗
- 运行 lstm.sh 时 -CUDA_VISIBLE_DEVICES 参数是否与你机器中想用的 GPU 一致

希望对你有所帮助
